# docker-compose file that allows RPCh exit node to run alongside HOPRd
version: "3"

volumes:
  hoprd-data:
  exit-node-data:

services:
  hoprd:
    image: gcr.io/hoprassociation/hoprd:sha256:822ead8398b00c2564e755f742dea218b92e9dacdc17b2eda2b6b9899631d3e3
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9091:9091"
      - "8080:8080"
    volumes:
      - hoprd-data:/tmp
    environment:
      - HOPRD_HOST=0.0.0.0:9091
      - HOPRD_API_HOST=0.0.0.0
      - HOPRD_ADMIN_HOST=0.0.0.0
      - HOPRD_ADMIN=true
      - HOPRD_API=true
      - HOPRD_INIT=true
      - HOPRD_ENVIRONMENT=${HOPRD_ENVIRONMENT}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - HOPRD_PASSWORD=${HOPRD_PASSWORD}
  exit-node:
    build:
      dockerfile: apps/exit-node/Dockerfile
      context: ../../
    depends_on:
      - hoprd
    restart: unless-stopped
    volumes:
      - exit-node-data:/tmp
    environment:
      - HOPRD_API_ENDPOINT=http://hoprd:3001
      - DEBUG=${DEBUG}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_PASSWORD}
      - RPCH_IDENTITY_DIR=${RPCH_IDENTITY_DIR}
      - RPCH_PRIVATE_KEY=${RPCH_PRIVATE_KEY}
      - RPCH_DATA_DIR=${RPCH_DATA_DIR}
    entrypoint:
      [
        "/bin/wait-for",
        "http://${HOPRD_API_TOKEN}@hoprd:3001/api/v2/account/addresses",
        "-t",
        "300",
        "--",
        "/sbin/tini",
        "--",
      ]
    command: "node apps/exit-node/build/index.js"
