# docker-compose file that allows RPCh exit node to run alongside HOPRd
version: "3"

volumes:
  hoprd-data:
  exit-node-data:

networks:
  hopr-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
services:
  hoprd:
    image: ${HOPRD_DOCKER_IMAGE}
    restart: on-failure
    pull_policy: always
    mem_reservation: 1g
    mem_limit: 4g
    container_name: hoprd
    hostname: hoprd
    networks:
      - hopr-net
    ports:
      - "3001:3001"
      - "9091:9091/tcp"
      - "9091:9091/udp"
      - "8080:8080"
    env_file:
        - .env-default
        - .env
    volumes:
      - '/opt/hoprd:/app/hoprd-db'
      - '/var/run/docker.sock:/var/run/docker.sock'
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
        max-file: "7"
  exit-node:
    build:
      dockerfile: apps/exit-node/Dockerfile
      context: ../../
    depends_on:
      - hoprd
    restart: unless-stopped
    volumes:
      - exit-node-data:${RPCH_DATA_DIR}
    environment:
      - HOPRD_API_ENDPOINT=http://hoprd:3001
      - DEBUG=${RPCH_DEBUG}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_PASSWORD}
      - RPCH_IDENTITY_FILE=${RPCH_IDENTITY_FILE}
      - RPCH_PRIVATE_KEY=${RPCH_PRIVATE_KEY}
      - RPCH_DATA_DIR=${RPCH_DATA_DIR}
      - OPT_IN_METRICS=${OPT_IN_METRICS}
    networks:
      - hopr-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "7"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    expose:
      - 9093
    ports:
      - 9093:8080
    networks:
      - hopr-net
    devices:
      - /dev/kmsg:/dev/kmsg
  nodeexporter:
    image: prom/node-exporter:v1.4.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - hopr-net
