# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 funding service
#   - 1 discovery platform
#   - 1 postgres DB
version: "3"

volumes:
  # postgres database
  postgres-data:

services:
  postgres-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - sandbox-proxy
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # funding-service:
  #   build:
  #     dockerfile: apps/funding-service/Dockerfile
  #     context: ../../../
  #   depends_on:
  #     - postgres-db
  #   restart: unless-stopped
  #   ports:
  #     - "3010:3010"
  #   networks:
  #     - sandbox-proxy
  #   environment:
  #     - DEBUG=${DEBUG}
  #     - PORT=3010
  #     - SECRET_KEY=${SECRET_KEY}
  #     - WALLET_PRIV_KEY=${FUNDING_SERVICE_PRIVATE_KEY}
  #     - DB_CONNECTION_URL=postgresql://postgres:postgres@postgres-db:5432
  #     - FORCE_CHAIN_ID=31337
  #     - FORCE_RPC_URL=${RPC_PROVIDER}
  #     - FORCE_SMART_CONTRACT_ADDRESS=${FORCE_SMART_CONTRACT_ADDRESS}

  discovery-platform:
    build:
      dockerfile: apps/discovery-platform/Dockerfile
      context: ../../../
    depends_on:
      - postgres-db
    restart: unless-stopped
    ports:
      - "3020:3020"
    networks:
      - sandbox-proxy
    environment:
      - DEBUG=${DEBUG}
      - PORT=3020
      - SECRET_KEY=${SECRET_KEY}
      - DB_CONNECTION_URL=postgresql://postgres:postgres@postgres-db:5432
      - FUNDING_SERVICE_URL=http://funding-service:3010
      - SKIP_CHECK_COMMITMENT=${SKIP_CHECK_COMMITMENT}

# we create a proxy to the sandbox
# network created in 'nodes-docker-compose'
networks:
  sandbox-proxy:
    name: sandbox
    external: true
