# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 availability monitor
version: "4"

volumes:
  # postgres database
  postgres-data:

services:
  availability-monitor:
    build:
      dockerfile: apps/availability-monitor/Dockerfile
      context: ../../../
    restart: unless-stopped
    ports:
      - "9080:9080"
    networks:
      - rpch-sandbox
    environment:
      - DEBUG=${DEBUG}
      - PORT=9080
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432
  # rpc-server:
  #   build:
  #     dockerfile: apps/rpc-server/Dockerfile
  #     context: ../../../
  #   restart: unless-stopped
  #   ports:
  #     - "45750:45750"
  #   networks:
  #     - rpch-sandbox
  #   environment:
  #     - DEBUG=${DEBUG}
  #     - LOG_LEVEL=verbose
  #     - CLIENT=foobarfoobar
  #     - PORT=45750
  #     - DISCOVERY_PLATFORM_API_ENDPOINT=http://host.docker.internal:3020
  #     - FORCE_ZERO_HOP=true

# we create a proxy to the sandbox
# network created in 'nodes-docker-compose'
networks:
 rpch-sandbox:
    name: rpch-sandbox
    driver: bridge
    external: true
