# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 availability monitor
version: "4"

volumes:
  # postgres database
  postgres-data:

services:
  availability-monitor:
    build:
      dockerfile: apps/availability-monitor/Dockerfile
      context: ../../../
    restart: unless-stopped
    ports:
      - "9080:9080"
    networks:	
      - rpch-sandbox
    environment:
      - DEBUG=${DEBUG}
      - PORT=9080
      - DATABASE_URL=${DATABASE_URL}

networks:	
  rpch-sandbox:	
    name: rpch-sandbox	
    external: true