# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 availability monitor
version: "4"

services:
  rpc-server:
    build:
      dockerfile: apps/rpc-server/Dockerfile
      context: ../../../
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "45750:45750"
    extra_hosts:
     - "localhost:${PLUTO_IP}"
    environment:
      - DEBUG_COLORS=false
      - LOG_LEVEL=verbose
      - CLIENT=foobarfoobar
      - DISCOVERY_PLATFORM_API_ENDPOINT=http://discovery-platform:3020
      - FORCE_ZERO_HOP=true

networks:	
  rpch-sandbox:	
    name: rpch-sandbox	
    external: true