# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 discovery platform
#   - 1 postgres DB
version: "4"

volumes:
  # postgres database
  postgres-data:

services:
  postgres-db-rpch:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
#    network_mode: bridge
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      - rpch-sandbox
    volumes:
      - postgres-data:/var/lib/postgresql/data

  discovery-platform:
    build:
      dockerfile: apps/discovery-platform/Dockerfile
      context: ../../../
    depends_on:
      - postgres-db-rpch
    restart: unless-stopped
    ports:
      - "3020:3020"
    network_mode: host
#    network:
#      - host
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    networks:
#      - rpch-sandbox
    environment:
      - DEBUG=${DEBUG}
      - URL=http://127.0.0.1:3020
      - PORT=3020
      - DATABASE_URL=${DATABASE_URL}
#      - FUNDING_SERVICE_URL=http://host.docker.internal:3010
#      - AVAILABILITY_MONITOR_URL=http:/availability-monitor:9080
      - SKIP_CHECK_COMMITMENT=${SKIP_CHECK_COMMITMENT}
      - ADMIN_SECRET=${ADMIN_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - RUNNING_IN_SANDBOX=${RUNNING_IN_SANDBOX}
      - DISCOVERY_PLATFORM_ACCESS_TOKEN=${DISCOVERY_PLATFORM_ACCESS_TOKEN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
