# docker-compose file that allows you locally host
# the centralized apps that make RPCh work
# DO NOT USE IN PRODUCTION
# launches:
#   - 1 availability monitor
version: "4"

services:
  rpc-server:
  #  build:
  #    dockerfile: apps/rpc-server/Dockerfile
  #    context: ../../../

  # TODO fix:
  #     env: ‘bash\r’: No such file or directory
  #     env: use -[v]S to pass options in shebang lines
  # from apps/rpc-server/Dockerfile 
  
    image: europe-west6-docker.pkg.dev/rpch-375921/rpch/rpc-server@sha256:09b2b17d6c079edef1e6910dc4778d7f21fb2374a4a945d5aaa233887d1d9af0
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "45750:45750"
    environment:
      - DEBUG_COLORS=false
      - LOG_LEVEL=verbose
      - CLIENT=foobarfoobar
      - DISCOVERY_PLATFORM_API_ENDPOINT=http://host.docker.internal:3020
      - FORCE_ZERO_HOP=true

