# docker-compose file that allows you locally host
# 5 HOPRd nodes and 5 exit nodes attached to each other
# DO NOT USE IN PRODUCTION
version: "3"

volumes:
  # hoprd node identity files
  pluto-data: # exit node identity files
  exit-node-data:

x-exit-service: &exit
  build:
    dockerfile: apps/exit-node/Dockerfile
    context: ../../../
  restart: unless-stopped
  volumes:
    - exit-node-data:/tmp
  depends_on:
    - pluto
  command: "node apps/exit-node/build/index.js"

services:
  pluto:
    image: gcr.io/hoprassociation/hopr-pluto:v1.92.7@sha256:1ae8c8602cf9183ee44f46b0bf12b977d75ae08a2bff22f67bd2cedb5f7db253
    restart: unless-stopped
    volumes:
      - pluto-data:/tmp
    ports:
      # mapping admin and api ports to localhost for app developers to access
      # the admin UI more easily
      - "13301-13305:13301-13305"
      - "19501-19505:19501-19505"
      # local RPC port
      - "8545:8545"
    environment:
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
  exit-1:
    <<: *exit
    environment:
      - HOPRD_API_ENDPOINT=http://pluto:13301
      - DEBUG=${DEBUG:-"rpch*"}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_EXIT_NODE_PASSWORD}
    entrypoint:
      [
        "/bin/wait-for",
        "http://${HOPRD_API_TOKEN}@pluto:13301/api/v2/account/addresses",
        "-t",
        "300",
        "--",
        "/sbin/tini",
        "--",
      ]
  exit-2:
    <<: *exit
    environment:
      - HOPRD_API_ENDPOINT=http://pluto:13302
      - DEBUG=${DEBUG:-"rpch*"}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_EXIT_NODE_PASSWORD}
    entrypoint:
      [
        "/bin/wait-for",
        "http://${HOPRD_API_TOKEN}@pluto:13302/api/v2/account/addresses",
        "-t",
        "300",
        "--",
        "/sbin/tini",
        "--",
      ]
  exit-3:
    <<: *exit
    environment:
      - HOPRD_API_ENDPOINT=http://pluto:13303
      - DEBUG=${DEBUG:-"rpch*"}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_EXIT_NODE_PASSWORD}
    entrypoint:
      [
        "/bin/wait-for",
        "http://${HOPRD_API_TOKEN}@pluto:13303/api/v2/account/addresses",
        "-t",
        "300",
        "--",
        "/sbin/tini",
        "--",
      ]
  exit-4:
    <<: *exit
    environment:
      - HOPRD_API_ENDPOINT=http://pluto:13304
      - DEBUG=${DEBUG:-"rpch*"}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_EXIT_NODE_PASSWORD}
    entrypoint:
      [
        "/bin/wait-for",
        "http://${HOPRD_API_TOKEN}@pluto:13304/api/v2/account/addresses",
        "-t",
        "300",
        "--",
        "/sbin/tini",
        "--",
      ]
  exit-5:
    <<: *exit
    environment:
      - HOPRD_API_ENDPOINT=http://pluto:13305
      - DEBUG=${DEBUG:-"rpch*"}
      - HOPRD_API_TOKEN=${HOPRD_API_TOKEN}
      - RPCH_PASSWORD=${RPCH_EXIT_NODE_PASSWORD}
    entrypoint:
      [
        "/bin/wait-for",
        "http://${HOPRD_API_TOKEN}@pluto:13305/api/v2/account/addresses",
        "-t",
        "300",
        "--",
        "/sbin/tini",
        "--",
      ]
