apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-platform.fullname" . }}
  labels:
    {{- include "discovery-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "discovery-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "discovery-platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "discovery-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "development"
            - name: HOPRD_ACCESS_TOKEN
              value: "^^awesomeHOPRr3l4y^^"
            - name: FUNDING_SERVICE_URL
              value: http://funding-service.funding-service:3010
            - name: DEBUG
              value: "hopr*,rpch*,-*verbose,-*metrics"
            - name: SECRET_KEY
              value: "PleaseChangeMe"
            - name: WALLET_PRIV_KEY
              value: "0x97c7a7bdca6d4fdf1549f586971ff8744a70c5fd9b2a6d83d8dd1ca3d894a748"
            - name: DB_CONNECTION_URL
              value: "postgresql://postgresql:postgresql@postgresql.postgresql:5432"
            - name: SMART_CONTRACT_ADDRESS
              value: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
            - name: PORT
              value: "3020"
          ports:
            - name: http
              containerPort: 3020
              protocol: TCP
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /*/}}
{{/*              port: http*/}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
