apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-platform.fullname" . }}
  labels:
    {{- include "discovery-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3020
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "discovery-platform.selectorLabels" . | nindent 4 }}
