name: "Build RPCh monorepo"
description: "Build the RPCh monorepo"

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.2.0
        large-packages: false
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "yarn"
        cache-dependency-path: ./yarn.lock
        registry-url: "https://registry.npmjs.org/"

    - name: Install dependencies
      shell: bash
      run: yarn

    - name: Build
      shell: bash
      run: yarn build
