name: exit-node

#TODO - check if we can somehow get over GitHub limitation of only one 'on' per workflow
on:
  push:
    paths:
      - apps/exit-node/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #We need this to be checked out here as well
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build container image
        uses: "./.github/actions/build-container"
        with:
          dockerfile: "apps/exit-node/Dockerfile"
          image: "sitilge/exit-node"
          registry: "docker.io"
          user: ${{ secrets.CONTAINER_REGISTRY_USER }}
          secret: ${{ secrets.CONTAINER_REGISTRY_SECRET }}