name: Review

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  review:
    name: Review
    needs: build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Review linting
        run: yarn lint

      - name: Review formatting
        run: yarn format

      - name: Run tests and coverage
        run: yarn test --ci
