name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Review linting
        run: yarn lint

      - name: Review formatting
        run: yarn format

      - name: Run Tests
        run: yarn test --ci

      - name: Run Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          package-manager: yarn
          test-script: yarn coverage
          output: report-markdown

      - name: Sticky coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # pass output from the previous step by id.
          message: ${{ steps.coverage.outputs.report }}
