name: Review

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    name: Review
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      # enable remote caching using turbo
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Build
        uses: ./.github/actions/build-rpch
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Review linting
        run: yarn lint

      - name: Review formatting
        run: yarn format

      - name: Run tests and coverage
        run: yarn test --ci

      # - name: Run E2E tests
      #   run: yarn test:e2e
