name: sandbox

#TODO - check if we can somehow get over GitHub limitation of only one 'on' per workflow
on:
  push:
    paths:
      - devkit/sandbox/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #We need this to be checked out here as well
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build container image
        uses: "./.github/templates/build-container"
        with:
          dockerfile: "devkit/sandbox/Dockerfile"
          image: "sitilge/sandbox"
          registry: "docker.io"
          user: ${{ secrets.CONTAINER_REGISTRY_USER }}
          secret: ${{ secrets.CONTAINER_REGISTRY_SECRET }}